version: '3'

services:
  frontend:
    image: frontend
    ports:
      - "3000:3000"
  api-server:
    image: api-server
    ports:
      - "5000:5000"
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: rishix23
      MONGO_INITDB_ROOT_PASSWORD: Absegami16!
      MONGO_INITDB_DATABASE: test
    volumes:
      - ./data:/data/db
